var objEnum = {
    ClsBllInvoiceStatus:{ 
        STATUS_DRAFT: 'LNG_ENUM_STATUS_DRAFT',
        STATUS_SENT: 'LNG_ENUM_STATUS_SENT',
        STATUS_OVERDUE: 'LNG_ENUM_STATUS_OVERDUE',
        STATUS_PARTIAL: 'LNG_ENUM_STATUS_PARTIAL',
        STATUS_PAID: 'LNG_ENUM_STATUS_PAID',
        STATUS_WRITE_OFF: 'LNG_ENUM_STATUS_WRITE_OFF',
        STATUS_VOID: 'LNG_ENUM_STATUS_VOID',
    },ClsBllTaxType:{
        TYPE_FIXED: 'LNG_ENUM_FIXED',
        TYPE_PERCENT: 'LNG_ENUM_PERCENT'
    },
    ClsBllInvoiceRowType:{         
        ROW_TYPE_ITEM: 'LNG_ENUM_ITEM',
        ROW_TYPE_DISCOUNT: 'LNG_ENUM_DISCOUNT',
        ROW_TYPE_TAX: 'LNG_ENUM_TAX',
    },
};